### ISSUE TITLE
Is this project still maintained?

### ISSUE THREAD

**Issue by Robsta86** [koenieee/Grocy-Picnic#1]
Hi koenieee,

I stumbled upon your project and I like the idea of connecting Picnic with Grocy. An amazing job you've done so far. I was wondering if this code on Github is the latest version of the project, or did you do more developments offline?

I noticed that there are quite some changes needed to make this work now since the Picnic API seems to be changed, and some of the issues I am running into might have been caused by a newer version of Grocy (3.3.0).

If you have a newer version offline would  you be so kind to push it to Git? If not I might make a fork and try to get things working myself :-)

**Comment by koenieee** [comment]
Hi Robsta86,

At the moment I spend my time on a new project so this one is up to date. I stil like the idea so I would be very nice if you would like to continue my work. Maybe someday I can help again.
btw there is also a Grocy Python implementation, I wrote one myself but that isn't really neccessary.

**Comment by Robsta86** [comment]
Thank you for taking the time to reply 👍 I have forked your project and I'll give it a go! 
Good luck with your new project!
